# Human-friendly inventory.
# This will be converted to file_sd JSON for Prometheus.
targets:
  - name: ecs-1
    address: 192.168.0.102
    mode: ssh
    labels:
      role: web

  - name: redis-1
    address: 192.168.0.113
    mode: ssh
    labels:
      role: redis