targets:
  - name: ecs-1
    address: 192.168.0.102
    labels:
      role: web
    ssh:
      user: root
      auth:
        password_file: /run/secrets/ecs-1.pass

  - name: redis-1
    address: 192.168.0.113
    labels:
      role: redis
    ssh:
      user: root
      auth:
        password_file: /run/secrets/redis-1.pass
